#!/usr/bin/env bash
#script to create a file containing the script's PID...
i=1
echo "$$" > /var/run/myscript.pid
while [ $i ]
do
	echo "To infinity and beyond"
	sleep 1
	trap "echo 'I hate the kill command'; rm /var/run/myscript.pid; exit" SIGTERM
	trap "echo 'Y U no love me?!'" SIGINT
	trap "rm /var/run/myscript.pid; exit" SIGQUIT
done
