#!/usr/bin/env bash
# Bash script that  installs the 'ufw' firewall.

apt-get install ufw

ufw enable
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp
ufw allow 443/tcp
ufw allow 80/tcp
